-- Crazilo initial content seed
-- Seeds verified public content from the repository into the deployed schema.

begin;

-- ============================================================================
-- SITE SETTINGS
-- ============================================================================
insert into public.site_settings (
  scope,
  store_name,
  support_phone,
  support_email,
  support_address,
  support_hours,
  footer_description,
  free_shipping_threshold,
  currency_code,
  instagram_url,
  facebook_url,
  twitter_url,
  youtube_url,
  privacy_policy_url,
  terms_url,
  returns_policy_url,
  store_locator_url,
  faqs_url
)
values (
  'global',
  'Crazilo',
  '+91 98765 43210',
  'hello@crazilo.com',
  'Mumbai, Maharashtra, India',
  'Mon–Sat, 9am–6pm IST',
  'Premium quality dry fruits, nuts, and spices sourced directly from Kashmir and top Indian farms. Bringing nature''s finest harvests to your doorstep since 2020.',
  599,
  'INR',
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null
)
on conflict (scope) do update set
  store_name = excluded.store_name,
  support_phone = excluded.support_phone,
  support_email = excluded.support_email,
  support_address = excluded.support_address,
  support_hours = excluded.support_hours,
  footer_description = excluded.footer_description,
  free_shipping_threshold = excluded.free_shipping_threshold,
  currency_code = excluded.currency_code,
  instagram_url = excluded.instagram_url,
  facebook_url = excluded.facebook_url,
  twitter_url = excluded.twitter_url,
  youtube_url = excluded.youtube_url,
  privacy_policy_url = excluded.privacy_policy_url,
  terms_url = excluded.terms_url,
  returns_policy_url = excluded.returns_policy_url,
  store_locator_url = excluded.store_locator_url,
  faqs_url = excluded.faqs_url,
  updated_at = timezone('utc', now());

-- ============================================================================
-- CATEGORIES
-- ============================================================================
insert into public.categories (
  id,
  name,
  slug,
  description,
  image_url,
  icon_url,
  parent_id,
  sort_order,
  is_active,
  meta_title,
  meta_description,
  created_at,
  updated_at
)
values
  (
    '11111111-1111-1111-1111-111111111111',
    'Dry Fruits',
    'dry-fruits',
    null,
    '/images/cat-dryfruits.png',
    null,
    null,
    1,
    true,
    null,
    null,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    '22222222-2222-2222-2222-222222222222',
    'Nuts',
    'nuts',
    null,
    '/images/cat-nuts.png',
    null,
    null,
    2,
    true,
    null,
    null,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    '33333333-3333-3333-3333-333333333333',
    'Seeds',
    'seeds',
    null,
    null,
    null,
    null,
    3,
    true,
    null,
    null,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    '44444444-4444-4444-4444-444444444444',
    'Spices',
    'spices',
    null,
    '/images/cat-spices.png',
    null,
    null,
    4,
    true,
    null,
    null,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    '55555555-5555-5555-5555-555555555555',
    'Trail Mixes',
    'trail-mixes',
    null,
    null,
    null,
    null,
    5,
    true,
    null,
    null,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    '66666666-6666-6666-6666-666666666666',
    'Combos',
    'combos',
    null,
    '/images/cat-combos.png',
    null,
    null,
    6,
    true,
    null,
    null,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    '77777777-7777-7777-7777-777777777777',
    'Gift Boxes',
    'gift-boxes',
    null,
    '/images/cat-gifts.png',
    null,
    null,
    7,
    true,
    null,
    null,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    '88888888-8888-8888-8888-888888888888',
    'Makhana',
    'makhana',
    null,
    '/images/cat-makhana.png',
    null,
    null,
    8,
    true,
    null,
    null,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    '11111111-1111-1111-1111-111111111112',
    'Cashews',
    'cashews',
    null,
    null,
    null,
    '11111111-1111-1111-1111-111111111111',
    1,
    true,
    null,
    null,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    '11111111-1111-1111-1111-111111111113',
    'Almonds',
    'almonds',
    null,
    null,
    null,
    '11111111-1111-1111-1111-111111111111',
    2,
    true,
    null,
    null,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    '11111111-1111-1111-1111-111111111114',
    'Pistachios',
    'pistachios',
    null,
    null,
    null,
    '11111111-1111-1111-1111-111111111111',
    3,
    true,
    null,
    null,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    '11111111-1111-1111-1111-111111111115',
    'Walnuts',
    'walnuts',
    null,
    null,
    null,
    '11111111-1111-1111-1111-111111111111',
    4,
    true,
    null,
    null,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    '11111111-1111-1111-1111-111111111116',
    'Raisins',
    'raisins',
    null,
    null,
    null,
    '11111111-1111-1111-1111-111111111111',
    5,
    true,
    null,
    null,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    '11111111-1111-1111-1111-111111111117',
    'Dates',
    'dates',
    null,
    null,
    null,
    '11111111-1111-1111-1111-111111111111',
    6,
    true,
    null,
    null,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    '11111111-1111-1111-1111-111111111118',
    'Dried Berries',
    'dried-berries',
    null,
    null,
    null,
    '11111111-1111-1111-1111-111111111111',
    7,
    true,
    null,
    null,
    timezone('utc', now()),
    timezone('utc', now())
  )
on conflict (id) do update set
  name = excluded.name,
  slug = excluded.slug,
  description = excluded.description,
  image_url = excluded.image_url,
  icon_url = excluded.icon_url,
  parent_id = excluded.parent_id,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  meta_title = excluded.meta_title,
  meta_description = excluded.meta_description,
  updated_at = excluded.updated_at;

-- ============================================================================
-- BANNERS
-- ============================================================================
insert into public.banners (
  id,
  title,
  subtitle,
  badge_text,
  image_url,
  mobile_image_url,
  cta_text,
  cta_link,
  display_order,
  is_active,
  bg_color,
  text_color,
  starts_at,
  ends_at,
  created_at,
  updated_at
)
values (
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
  'GOODNESS, PACKED WITH FLAVOUR.',
  'Carefully sourced, hygienically processed and perfectly packed for your everyday goodness.',
  'PREMIUM DRY FRUITS',
  '/images/hero-cashews.png',
  '/images/hero-cashews.png',
  'SHOP DRY FRUITS',
  '/category/dry-fruits',
  1,
  true,
  '#8B0000',
  '#FFFFFF',
  null,
  null,
  timezone('utc', now()),
  timezone('utc', now())
)
on conflict (id) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  badge_text = excluded.badge_text,
  image_url = excluded.image_url,
  mobile_image_url = excluded.mobile_image_url,
  cta_text = excluded.cta_text,
  cta_link = excluded.cta_link,
  display_order = excluded.display_order,
  is_active = excluded.is_active,
  bg_color = excluded.bg_color,
  text_color = excluded.text_color,
  starts_at = excluded.starts_at,
  ends_at = excluded.ends_at,
  updated_at = excluded.updated_at;

-- ============================================================================
-- ANNOUNCEMENTS
-- ============================================================================
insert into public.announcements (
  id,
  text,
  link,
  display_order,
  is_active,
  created_at,
  updated_at
)
values (
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
  'Free shipping on orders above ₹999',
  '/products',
  1,
  true,
  timezone('utc', now()),
  timezone('utc', now())
)
on conflict (id) do update set
  text = excluded.text,
  link = excluded.link,
  display_order = excluded.display_order,
  is_active = excluded.is_active,
  updated_at = excluded.updated_at;

-- ============================================================================
-- TESTIMONIALS
-- ============================================================================
insert into public.testimonials (
  id,
  name,
  location,
  rating,
  text,
  product_name,
  avatar_initial,
  avatar_url,
  display_order,
  is_active,
  created_at,
  updated_at
)
values
  (
    'cccccccc-cccc-cccc-cccc-cccccccccc01',
    'Priya Sharma',
    'Mumbai',
    5,
    'The quality of almonds and cashews from Crazilo is absolutely amazing! Fresh, crunchy and so tasty. My family has made this our go-to brand for all dry fruits.',
    'Premium Almonds',
    'P',
    null,
    1,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    'cccccccc-cccc-cccc-cccc-cccccccccc02',
    'Rahul Mehta',
    'Delhi',
    5,
    'Ordered the spice combo and it arrived fresh and beautifully packaged. The smell alone tells you these are genuine quality spices. Will order again!',
    'Spice Combo Pack',
    'R',
    null,
    2,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    'cccccccc-cccc-cccc-cccc-cccccccccc03',
    'Anita Patel',
    'Ahmedabad',
    5,
    'I was skeptical at first but after one order I''m hooked! The makhana is so crispy and fresh. Great prices too. Highly recommend Crazilo to everyone.',
    'Premium Makhana',
    'A',
    null,
    3,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    'cccccccc-cccc-cccc-cccc-cccccccccc04',
    'Vikram Singh',
    'Bangalore',
    5,
    'Fast delivery and amazing packaging. The gift box I ordered for Diwali was a huge hit with everyone. Crazilo has become my default gifting choice!',
    'Premium Gift Box',
    'V',
    null,
    4,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    'cccccccc-cccc-cccc-cccc-cccccccccc05',
    'Meera Krishnan',
    'Chennai',
    4,
    'Love the variety and quality. The trail mix is perfect for my morning snack. Customer service was very responsive when I had a query. Great brand!',
    'Trail Mix Combo',
    'M',
    null,
    5,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  )
on conflict (id) do update set
  name = excluded.name,
  location = excluded.location,
  rating = excluded.rating,
  text = excluded.text,
  product_name = excluded.product_name,
  avatar_initial = excluded.avatar_initial,
  avatar_url = excluded.avatar_url,
  display_order = excluded.display_order,
  is_active = excluded.is_active,
  updated_at = excluded.updated_at;

-- ============================================================================
-- HOME FEATURE CARDS
-- ============================================================================
insert into public.home_feature_cards (
  id,
  section_key,
  eyebrow_text,
  title,
  subtitle,
  description,
  image_url,
  category_id,
  link_url,
  display_order,
  is_active,
  created_at,
  updated_at
)
values
  (
    'dddddddd-dddd-dddd-dddd-dddddddddd01',
    'find_your_snack',
    '100% Natural',
    'Daily Wellness',
    'Wholesome snacks for everyday nourishment...',
    null,
    'https://images.unsplash.com/photo-1543362906-acfc16c67564?auto=format&fit=crop&w=600&q=80',
    '11111111-1111-1111-1111-111111111111',
    '/category/dry-fruits',
    1,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    'dddddddd-dddd-dddd-dddd-dddddddddd02',
    'find_your_snack',
    'Festive Pack',
    'Gifting? Easy!',
    'Bundles, combos and a lot more for your loved ones...',
    null,
    'https://images.unsplash.com/photo-1508061252227-142f1f5d6df4?auto=format&fit=crop&w=600&q=80',
    '77777777-7777-7777-7777-777777777777',
    '/category/gift-boxes',
    2,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    'dddddddd-dddd-dddd-dddd-dddddddddd03',
    'find_your_snack',
    'High Protein',
    'Protein Power',
    'High protein snacks and super foods for the energy.',
    null,
    'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80',
    '55555555-5555-5555-5555-555555555555',
    '/category/trail-mixes',
    3,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    'dddddddd-dddd-dddd-dddd-dddddddddd04',
    'find_your_snack',
    'Low Calorie',
    'Guilt-free Snacks',
    'Low calorie snacks to beat the cravings.',
    null,
    'https://images.unsplash.com/photo-1608797178974-15b35a64ede9?auto=format&fit=crop&w=600&q=80',
    '88888888-8888-8888-8888-888888888888',
    '/category/makhana',
    4,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    'dddddddd-dddd-dddd-dddd-dddddddddd05',
    'featured_collections',
    'Dry Fruits',
    'Date Bites',
    'Chew Your Brew',
    '100% Natural Date & Nut Delights â€¢ No Added Sugar',
    'https://images.unsplash.com/photo-1543362906-acfc16c67564?auto=format&fit=crop&w=800&q=80',
    '11111111-1111-1111-1111-111111111111',
    '/category/dry-fruits',
    1,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    'dddddddd-dddd-dddd-dddd-dddddddddd06',
    'featured_collections',
    'Trail Mixes',
    'Dry Fruit Mixes',
    'Power Up Seeds & Berries',
    'Original Trail Mix â€¢ Berry Delight â€¢ Power Seed Mix',
    'https://images.unsplash.com/photo-1508061252227-142f1f5d6df4?auto=format&fit=crop&w=800&q=80',
    '55555555-5555-5555-5555-555555555555',
    '/category/trail-mixes',
    2,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    'dddddddd-dddd-dddd-dddd-dddddddddd07',
    'featured_collections',
    'Makhana',
    'Roasted Makhana',
    'Crunchy Salt & Peri Peri',
    'Cream & Onion â€¢ Peri Peri â€¢ Himalayan Salt Roasted',
    'https://images.unsplash.com/photo-1608797178974-15b35a64ede9?auto=format&fit=crop&w=800&q=80',
    '88888888-8888-8888-8888-888888888888',
    '/category/makhana',
    3,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    'dddddddd-dddd-dddd-dddd-dddddddddd08',
    'featured_collections',
    'Seeds',
    'Premium Seeds',
    'Sunflower, Pumpkin & Chia',
    'Raw & Roasted Chia, Pumpkin, Flax & Sunflower Seeds',
    'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80',
    '33333333-3333-3333-3333-333333333333',
    '/category/seeds',
    4,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  )
on conflict (id) do update set
  section_key = excluded.section_key,
  eyebrow_text = excluded.eyebrow_text,
  title = excluded.title,
  subtitle = excluded.subtitle,
  description = excluded.description,
  image_url = excluded.image_url,
  category_id = excluded.category_id,
  link_url = excluded.link_url,
  display_order = excluded.display_order,
  is_active = excluded.is_active,
  updated_at = excluded.updated_at;

-- ============================================================================
-- HOME HIGHLIGHTS
-- ============================================================================
insert into public.home_highlights (
  id,
  icon_key,
  title,
  description,
  display_order,
  is_active,
  created_at,
  updated_at
)
values
  (
    'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee01',
    'hero_100_natural',
    '100% Natural',
    'Pure harvested goodness',
    1,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee02',
    'hero_premium_quality',
    'Premium Quality',
    'Triple sorted & graded',
    2,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee03',
    'hero_freshly_packed',
    'Freshly Packed',
    'Hygienic nitropack',
    3,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee04',
    'hero_no_preservatives',
    'No Preservatives',
    'Zero chemicals added',
    4,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee05',
    'why_100_natural',
    '100% Natural',
    'No artificial colors, flavors, or preservatives. Pure nature in every bite.',
    10,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee06',
    'why_premium_quality',
    'Premium Quality',
    'Carefully sourced from the best farms and orchards across India.',
    11,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee07',
    'why_fast_delivery',
    'Fast Delivery',
    'Free shipping above â‚¹599. Same-day dispatch on orders before 2 PM.',
    12,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee08',
    'why_safe_sealed',
    'Safe & Sealed',
    'Hygienic vacuum-sealed packaging to preserve freshness and nutrition.',
    13,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee09',
    'why_easy_returns',
    'Easy Returns',
    'Not happy? Return within 7 days for a full refund, no questions asked.',
    14,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  ),
  (
    'eeeeeeee-eeee-eeee-eeee-eeeeeeeeee10',
    'why_customer_first',
    'Customer First',
    'Rated 4.9â˜… by over 50,000 happy customers across India.',
    15,
    true,
    timezone('utc', now()),
    timezone('utc', now())
  )
on conflict (id) do update set
  icon_key = excluded.icon_key,
  title = excluded.title,
  description = excluded.description,
  display_order = excluded.display_order,
  is_active = excluded.is_active,
  updated_at = excluded.updated_at;

-- ============================================================================
-- PRODUCTS
-- ============================================================================
insert into public.products (
  id,
  name,
  slug,
  description,
  short_description,
  category_id,
  price,
  compare_price,
  cost_price,
  sku,
  stock_quantity,
  low_stock_threshold,
  track_inventory,
  weight_grams,
  unit,
  images,
  thumbnail_url,
  is_active,
  is_featured,
  is_bestseller,
  is_new,
  is_organic,
  no_added_sugar,
  meta_title,
  meta_description,
  tags,
  nutritional_info,
  average_rating,
  review_count,
  total_sold
)
values
  (
    'f0000000-0000-0000-0000-000000000002',
    'CASHEW 180 GRADE',
    'cashew-180-grade',
    null,
    null,
    '11111111-1111-1111-1111-111111111112',
    199,
    249,
    null,
    null,
    0,
    10,
    false,
    null,
    'g',
    ARRAY['/images/cat-[#EFE7DD]cat-dryfruits.png']::text[],
    '/images/cat-[#EFE7DD]cat-dryfruits.png',
    true,
    true,
    true,
    false,
    false,
    false,
    null,
    null,
    ARRAY[]::text[],
    '{}'::jsonb,
    4.8,
    138,
    138
  ),
  (
    'f0000000-0000-0000-0000-000000000003',
    'CASHEW 240 GRADE',
    'cashew-240-grade',
    null,
    null,
    '11111111-1111-1111-1111-111111111112',
    229,
    279,
    null,
    null,
    0,
    10,
    false,
    null,
    'g',
    ARRAY['/images/hero-cashews.png']::text[],
    '/images/hero-cashews.png',
    true,
    true,
    true,
    false,
    false,
    false,
    null,
    null,
    ARRAY[]::text[],
    '{}'::jsonb,
    4.8,
    156,
    156
  ),
  (
    'f0000000-0000-0000-0000-000000000004',
    'CASHEW 320 GRADE',
    'cashew-320-grade',
    null,
    null,
    '11111111-1111-1111-1111-111111111112',
    259,
    319,
    null,
    null,
    0,
    10,
    false,
    null,
    'g',
    ARRAY['/images/cat-nuts.png']::text[],
    '/images/cat-nuts.png',
    true,
    true,
    true,
    false,
    false,
    false,
    null,
    null,
    ARRAY[]::text[],
    '{}'::jsonb,
    4.9,
    112,
    112
  ),
  (
    'f0000000-0000-0000-0000-000000000005',
    'CASHEW SALTED',
    'cashew-salted',
    null,
    null,
    '11111111-1111-1111-1111-111111111112',
    219,
    269,
    null,
    null,
    0,
    10,
    false,
    null,
    'g',
    ARRAY['/images/cat-[#EFE7DD]cat-dryfruits.png']::text[],
    '/images/cat-[#EFE7DD]cat-dryfruits.png',
    true,
    true,
    true,
    false,
    false,
    false,
    null,
    null,
    ARRAY[]::text[],
    '{}'::jsonb,
    4.7,
    94,
    94
  ),
  (
    'f0000000-0000-0000-0000-000000000006',
    'CASHEW CHILLY ROASTED',
    'cashew-chilly-roasted',
    null,
    null,
    '11111111-1111-1111-1111-111111111112',
    249,
    299,
    null,
    null,
    0,
    10,
    false,
    null,
    'g',
    ARRAY['/images/cat-spices.png']::text[],
    '/images/cat-spices.png',
    true,
    true,
    true,
    true,
    false,
    false,
    null,
    null,
    ARRAY[]::text[],
    '{}'::jsonb,
    4.8,
    98,
    98
  ),
  (
    'f0000000-0000-0000-0000-000000000007',
    'CASHEW PEPPER ROASTED',
    'cashew-pepper-roasted',
    null,
    null,
    '11111111-1111-1111-1111-111111111112',
    249,
    299,
    null,
    null,
    0,
    10,
    false,
    null,
    'g',
    ARRAY['/images/cat-nuts.png']::text[],
    '/images/cat-nuts.png',
    true,
    true,
    true,
    true,
    false,
    false,
    null,
    null,
    ARRAY[]::text[],
    '{}'::jsonb,
    4.8,
    87,
    87
  ),
  (
    'f0000000-0000-0000-0000-000000000008',
    'CASHEW GREEN CHILLY ROASTED',
    'cashew-green-chilly-roasted',
    null,
    null,
    '11111111-1111-1111-1111-111111111112',
    249,
    299,
    null,
    null,
    0,
    10,
    false,
    null,
    'g',
    ARRAY['/images/cat-spices.png']::text[],
    '/images/cat-spices.png',
    true,
    true,
    true,
    true,
    false,
    false,
    null,
    null,
    ARRAY[]::text[],
    '{}'::jsonb,
    4.7,
    76,
    76
  ),
  (
    'f0000000-0000-0000-0000-000000000009',
    'CASHEW BARBEQUE ROASTED',
    'cashew-barbeque-roasted',
    null,
    null,
    '11111111-1111-1111-1111-111111111112',
    249,
    299,
    null,
    null,
    0,
    10,
    false,
    null,
    'g',
    ARRAY['/images/cat-spices.png']::text[],
    '/images/cat-spices.png',
    true,
    true,
    true,
    true,
    false,
    false,
    null,
    null,
    ARRAY[]::text[],
    '{}'::jsonb,
    4.8,
    63,
    63
  ),
  (
    'f0000000-0000-0000-0000-00000000000a',
    'CHEESE ROASTED CASHEW',
    'cheese-roasted-cashew',
    null,
    null,
    '11111111-1111-1111-1111-111111111112',
    259,
    319,
    null,
    null,
    0,
    10,
    false,
    null,
    'g',
    ARRAY['/images/cat-[#EFE7DD]cat-dryfruits.png']::text[],
    '/images/cat-[#EFE7DD]cat-dryfruits.png',
    true,
    true,
    true,
    true,
    false,
    false,
    null,
    null,
    ARRAY[]::text[],
    '{}'::jsonb,
    4.8,
    82,
    82
  ),
  (
    'f0000000-0000-0000-0000-00000000000b',
    'BORMA CASHEW',
    'borma-cashew',
    null,
    null,
    '11111111-1111-1111-1111-111111111112',
    279,
    349,
    null,
    null,
    0,
    10,
    false,
    null,
    'g',
    ARRAY['/images/hero-cashews.png']::text[],
    '/images/hero-cashews.png',
    true,
    true,
    true,
    false,
    false,
    false,
    null,
    null,
    ARRAY[]::text[],
    '{}'::jsonb,
    4.9,
    91,
    91
  )
on conflict (id) do update set
  name = excluded.name,
  slug = excluded.slug,
  description = excluded.description,
  short_description = excluded.short_description,
  category_id = excluded.category_id,
  price = excluded.price,
  compare_price = excluded.compare_price,
  cost_price = excluded.cost_price,
  sku = excluded.sku,
  stock_quantity = excluded.stock_quantity,
  low_stock_threshold = excluded.low_stock_threshold,
  track_inventory = excluded.track_inventory,
  weight_grams = excluded.weight_grams,
  unit = excluded.unit,
  images = excluded.images,
  thumbnail_url = excluded.thumbnail_url,
  is_active = excluded.is_active,
  is_featured = excluded.is_featured,
  is_bestseller = excluded.is_bestseller,
  is_new = excluded.is_new,
  is_organic = excluded.is_organic,
  no_added_sugar = excluded.no_added_sugar,
  meta_title = excluded.meta_title,
  meta_description = excluded.meta_description,
  tags = excluded.tags,
  nutritional_info = excluded.nutritional_info,
  average_rating = excluded.average_rating,
  review_count = excluded.review_count,
  total_sold = excluded.total_sold,
  updated_at = excluded.updated_at;

commit;
